### ISSUE TITLE
Add support for fuzzy calendars

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#119]
- [x] Merge fuzzy calendars package with the main branch [@orlenyslp]
- [x] Integrate fuzzy calendars discovery and serialization for Prosimos [@iharsuvorau]
- [x] Integrate fuzzy calendars parameters optimization [@iharsuvorau]

**Comment by iharsuvorau** [comment]
Related PR https://github.com/AutomatedProcessImprovement/Simod/pull/125

**Comment by iharsuvorau** [comment]
Related commits c35d26ca6828039b3a8100a70af77975fc25e540, 6641720b84f7c3f1c49195ef5c94abaca0c83adc, 6641720b84f7c3f1c49195ef5c94abaca0c83adc, 8b6ce34bcdd456a846ebd37f4b13da5e4e1cb03d, 4ae0dbc9d0efe8347010aa2c5778375f0347995d, 76eeb9db57b72bf67912ae5f87a5e74532238d42, 3cd4990761982943590e35a69a06be4146f4e3b3, 7191f2b69d4946f94ccd3713ae6fd5ea528dc0b4, b41102ddb4269cad810587ab01d8261c106ca9dc, 217f6bc6a3030da54e4bae81bbca1670a53d36bd

**Comment by iharsuvorau** [comment]
@orlenyslp I see that the main function `build_fuzzy_calendars` discovers not only fuzzy calendars, but the full set of simulation parameters:

```python
    simulation_params = {
        "resource_profiles": build_resource_profiles(p_info),
        "arrival_time_distribution": distribution_to_json(arrival_dist),
        "arrival_time_calendar": arrival_calend.to_json(),
        "gateway_branching_probabilities": gateway_branching_to_json(gateways_branching),
        "task_resource_distribution": processing_times_json(res_task_distr, p_info.task_resources, p_info.bpmn_graph),
        "resource_calendars": join_fuzzy_calendar_intervals(p_info.fuzzy_calendars, p_info.i_size),
        "granule_size": {"value": i_size_minutes, "time_unit": "MINUTES"},
    }
```

I have a couple of questions because of that:

1. Is only `resource_calendars` the new thing here? Or format of other parameters has also changed? 
2. Does Prosimos already support running this new parameters?

**Comment by orlenyslp** [comment]
The new components in the model are "task_resource_distribution" and  "resource_calendars", as the processing times are also calculated according to the fuzzu_calendars discovered. The other components, "resource_profiles", "arrival_time_distribution", "arrival_time_calendar", and "gateway_branching_probabilities" uses the same discovery functions as the crisp model. Prosimos, already support them but that implementation is in the branch "fuzzy_calendars" in Prosimos. I am still working on merging it to the main branch, but there were several conflicts that I am still fixing. However, I think I will be done with it by tomorrow.

**Comment by iharsuvorau** [comment]
From now own, the fuzzy discovery is removed from this branch and Simod in general, and has moved to a pix-framework's branch at `12-add-support-for-fuzzy-calendars`. This is the issue for discussion, https://github.com/AutomatedProcessImprovement/pix-framework/issues/12.

This issue will continue with **optimization** of fuzzy parameters (resource calendars and activity-resource distributions).
