### ISSUE TITLE
Repair missing activities in Resource Model when Process Model is provided

### ISSUE THREAD

**Issue by david-chapela** [AutomatedProcessImprovement/Simod#129]
**Problem**: when SIMOD receive the process model as input (so it does not have to discover it), it can happen that the process model contains some activities that are not present in the (training) log used to discover the resource model. In this case, the simulation fails because the resource model has some missing activities (the ones present in the process model but not in the training log) and, thus, Prosimos doesn't know how to simulate their execution.

**Solution**: implement a "_repairing_" stage after SIMOD discovers the resource model to add a default model for each missing activity.

- [x] Implement, as part of Pix Framework, a method _repair\_with\_missing\_activities(resource\_model, model\_activities, event\_log)_ that receives the discovered resource model (potentially with missing activities), the activities present in the process model, and the (train\_validation) event log. For each activity in _model\_activities_ that is not in _resource\_model.resource\_activity\_performance_:
  1. Assign its name to _assigned\_tasks_ of each resource in each resource profile in _resource\_model.resource\_profiles_.
  2. Estimate the duration distribution of the activity from all its occurrences in _event\_log_.
  3. If the event log has no occurrences of this activity, assign a duration fixed of 1 second as default.
  4. Create a new instance in _resource\_model.resource\_activity\_performance_ for this activity, with the duration distribution estimated in the previous steps, for each of the resources.
- [x] If SIMOD received the process model as a parameter, call to _repair\_with\_missing\_activities()_ right after each time SIMOD is calling to _discover\_resource\_model()_, to repair possible missing activities. This should only be _i)_ in the beginning of SIMOD run, _ii)_ in each iteration of the Resource Model Optimizer, and _iii)_ in the end of SIMOD run (when discovering the final BPS model).
- [x] Test it with a couple of simple examples (we can create them, no need to add BPIC15\_1 to the test assets).

&nbsp;
&nbsp;
&nbsp;

_Possible future addition, perform the same repairing for Timer Events if they are included in the provided process model._

**Comment by david-chapela** [comment]
@iharsuvorau, if you need a log to test this, I would create a new method in [test_simod.py](https://github.com/AutomatedProcessImprovement/Simod/blob/master/tests/test_simod.py) to run Simod once with this [BPMN model](https://github.com/AutomatedProcessImprovement/Simod/blob/master/tests/assets/LoanApp_simplified.bpmn) (already in assets) and this [event log](https://github.com/AutomatedProcessImprovement/Simod/files/12196489/LoanApp_simplified_without_approve_loan_offer.csv) (I just filtered the one we have and removed one activity).

This simple test should check:
- [ ] It doesn't fail.
- [ ] The removed activity (Approve Loan Offer) is part of the simulated logs.
- [ ] The removed activity is part of the simulation parameters (all the resources can perform it, and there is an entry for it in the activity_resource_distributions).

This test won't check the case of the activity being present in some part of the log, and thus having a duration inferred from that. It only checks that the duration is the default one. But it should be enough, creating the other log is a bit more complicated and no need.

**Comment by iharsuvorau** [comment]
Blocked by an issue in the `pix-framework`'s calendar discovery, https://github.com/AutomatedProcessImprovement/pix-framework/issues/6.
