### ISSUE TITLE
Problem at runtime in windows Simod v2.0.0

### ISSUE THREAD

**Issue by mitushig3** [AutomatedProcessImprovement/Simod#50]
I am a student who tried to run the stable version of Simod from sometime back to try and see the results of the simulation on the input logs. However, I faced the following issue (see screenshot).

It does not seem to be an installation error, but something machine or OS dependent where it cannot read the output file produced during execution. I have also tried installing the new version of Simod which again gives me an error. Is there an existing solution to this problem available? 

Thanks. 
![error](https://user-images.githubusercontent.com/71011966/165731727-5d743485-f2a1-4966-9799-aa83116ad1e1.png)
![error4](https://user-images.githubusercontent.com/71011966/165731735-3748a7ed-906d-4452-bc23-fde5be15efde.png)

**Comment by iharsuvorau** [comment]
Hello, @mitushig3. Thanks for the interest. The previous version isn't supported. From the screenshot, it's also difficult for me to say what's the problem is. It says that a file is not found. Have you provided all the input?

The new version doesn't have the UI yet, but you can install it and use as a CLI-tool. The instructions are in the README. The Docker version, probably, would be easier to set up, because Simod has a set of Java and Python dependencies, that may complicate the installation.

**Comment by mitushig3** [comment]
I setup the docker version as you suggested. however, it still gives me a "File not found" error when I try to run any of the commands given in the README for the latest version. It seems it cannot find the "optimize_config.yml" file for example. Kindly direct me as to what I may be doing wrong because it does not seem to be an installation issue somehow (simod --help runs perfectly fine and so does simod command by itself).

**Comment by iharsuvorau** [comment]
@mitushig3 Just pushed a sample event log to `resources/event_log`. You might want to try that one.

**Comment by mitushig3** [comment]
I can finally make a successful run of the tool. Thank you for the prompt reply and the sample log to try. If I understand correctly, I can add the logs and modify the optimize_config to try out new logs like you have done for now? 

Also, on my first run I ran into another error where it cannot generate the output as "Purchasingexample.bpmn" and therefore gives the error of "FileNot Found" later when trying to optimize the parameters. Do you know why that would happen? Were you yourself able to run and generate the output model?

PS: I checked the folders in cmd and the output folders have been created with the IDs but no sign of  "Purchasingexample.bpmn" .
