### ISSUE TITLE
Missing scripts and logs from version 2.0.0

### ISSUE THREAD

**Issue by mitushig3** [AutomatedProcessImprovement/Simod#53]
Hello! 

I am tasked with reproducing and researching some findings from a paper in 2020 that used this particular tool (v. 2.0.0). They mention a script "Sweeper.py" which was used for the preprocessing of event logs and also the log as found in "multitasking_logs" folder. Even after downloading the old source files, I cannot find the specified files and really cannot move forward without especially the script. If any contributor has access to the data (eg. if they modified it at the time), kindly share if possible. The links mentioned in the research paper are no longer valid. 

old links for reference:
1. https://github.com/AdaptiveBProcess/Simod/tree/master/inputs/
multitasking_logs
2. https://github.com/AdaptiveBProcess/Simod/tree/master/support_modules/
multitasking

**Comment by mitushig3** [comment]
Thank you! I found the logs and scripts, successfully followed it for the adjustment of original logs but when I try to run the jupyter notebook I get the following error. Since you have a better understanding of how the application works, I was hoping you could tell me what's wrong/needs to be changed in the code maybe to fix this error (v. 2.1.0)? I prefer to stick to this version even if its old since I have to analyze logs and multitasking in a very specific way that is allowed by only the jupyter notebook interface and multitasking capabilities in the software.

**Comment by iharsuvorau** [comment]
Hi, @mitushig3. Unfortunately, we don't support all the previous versions of Simod. From the screenshot, I can see that the error is about `simod` module not having `single_exec` attribute. Which is correct, I checked simod.py, it doesn't have these modules.

**Comment by Mcamargo85** [comment]
Hi @mitushig3 that variable was used for select the kind of execution (single or optimizer) from the user interface. However the UI was disabled and deprecated just few weeks later and probably the backend got some changes that's what it is not working. Still you can reproduce the experiments using the console script from and IDE or from a console passing the required parameters.
 https://github.com/AutomatedProcessImprovement/Simod/blob/v2.1.0/simod_console.py
