### ISSUE TITLE
Refactoring evaluation metrics

### ISSUE THREAD

**Issue by iharsuvorau** [AutomatedProcessImprovement/Simod#63]
- [x] Remove all MAE metrics and TSD (leave only DL and DAY_HOUR_EMD).
- [x] DAY_HOUR_EMD is renamed to CIRCADIAN_EMD
- [x] Reimplement CIRCADIAN_EMD
- [x] Refactor `SimilarityEvaluator`

**Comment by iharsuvorau** [comment]
@david-chapela I've just pushed updates and leave the metrics until you reimplement the circadian EMD. Then, I can refactor the rest of `SimilarityEvaluator` just as DL computation and get rid of the whole class.

**Comment by david-chapela** [comment]
@iharsuvorau, I implemented the circadian one in the [Log Similarity Metrics repository](https://github.com/AutomatedProcessImprovement/log-similarity-metrics).

Not extensively tested, so let me know if you get any error. It works in the same way as the other EMD metrics.
