### ISSUE TITLE
Consider to use same training/validation in all the optimizations

### ISSUE THREAD

**Issue by david-chapela** [AutomatedProcessImprovement/Simod#71]
Currently, the training/validation split is being done twice, one in the Structure optimization phase, and a different one in the Time optimization phase.

This blocks SIMOD from using, in all the Time optimization iterations, the already discovered BPMN model and gateway probabilities from the Time optimization phase.

Possible performance improvement:
 - [x] At the start of the general optimization pipeline, split the logs into `training`/`validation`/`test`.
   - If we receive two input logs (training/test): split the training into `training`/`validation`, and use the test one as `test`.
   - If we receive only one input log: split this log into `training`/`validation`/`test` (from the input log, first get 80% for `training+validation` and 20% for `test`; then, from the `training+validation` split, get 80% for `training`, and 20% for `validation`).
 - [x] There is only one training log, and is the one used in all the phases for training.
 - [x] There is only one validation log, and is the one used in all the phases for evaluating each iteration.
 - [x] There is only one test log, and is the one used at the end of the SIMOD pipeline, to evaluate the final solution.
 - [x] The Structure optimization phase produces a BPMN model and its gateway probabilities (the probabilities, not the method) as a result.
   - If a BPMN model is provided as input, this phase only optimizes the gateway probabilities.
   - Otherwise, this phase optimizes both.
 - [x] The Time optimization phase uses the BPMN model and gateway probabilities (the file and the probability values) for each iteration of its optimization. It does not discover a new BPMN model in each iteration.

**Comment by iharsuvorau** [comment]
Hi @david-chapela. Here's a question about the structure optimization phase. Yes, before, one of the goals of the structure optimization was to determine either EQUIPROBABLE or DISCOVERY gateway probabilities method is better. In the search space for `fmin`, the gateway probabilities discovery *method* is used in optimization parameters, not probabilities itself. 

Here you ask to return *probabilities* from the structure optimizer instead of the method, but should we change the search space definition then too?

**Comment by david-chapela** [comment]
Hi @iharsuvorau. No, the optimization parameters are still the same, but now, we don't need to discover again the model. The calendar optimization is using the same training/validation logs, so we can directly use the BPMN model and gateway probabilities that we get (in memory) from the structure optimization.

So, the result of the structure optimization now is just the BPMN model and it's gateway probability values. These two are going to be used in all iterations of the calendar optimization.
